
[functions.contract-audit]
enabled = true
verify_jwt = true
import_map = "./functions/contract-audit/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/contract-audit/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/contract-audit/*.html" ]

[functions.contract-audit-v2]
enabled = true
verify_jwt = true
import_map = "./functions/contract-audit-v2/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/contract-audit-v2/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/contract-audit-v2/*.html" ]
